# Use different pre-set defaults than the global defaults.
#
# See `src/bootstrap/defaults` for more information.
# Note that this has no default value (x.py uses the defaults in `config.example.toml`).
profile = 'dist'
change-id = 127866

[llvm]

[build]

# Arguments passed to the `./configure` script, used during distcheck. You
# probably won't fill this in but rather it's filled in by the `./configure`
# script. Useful for debugging.
configure-args = ['--set', 'install.prefix=/opt/rust/1.81.0']

[install]

# Where to install the generated toolchain. Must be an absolute path.
prefix = '/opt/rust/1.81.0'

# Where to install system configuration files.
sysconfdir = "etc"

[rust]

[target.aarch64-apple-darwin]

[dist]

